all:
	
	
assembly:
	g++ -Wextra -Wall assembler.cpp common.cpp
	./a.out -a example.txt 290421res.xax
	
processing:
	g++ -Wextra -Wall processor.cpp common.cpp stack.cpp
	./a.out 290421res.xax proc_log.txt

run:	
	
debug:	
